In [3]:
import numpy as np
from numpy.linalg import solve

In [6]:
A1 = np.array([[1,2,1],[3,8,1],[0,4,1]])
b1 = np.array([2,12,2])
solve(A1,b1)

array([ 2.,  1., -2.])

In [44]:
#Identity Matrix
I = np.identity(3)
print(I)
#Elimination matrix 2,1 -> in python this is 0,1
E21 = np.copy(I)
E21[1,0] = -3
print(E21)
#Elimination matrix 3,2
E32 = np.copy(I)
E32[2,1] = -2
print(E32)
#To verify
result_step_1 = E21 @ A1
print(result_step_1)
result_step_2 = E32 @ result_step_1
print(result_step_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.  0.  0.]
 [-3.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -2.  1.]]
[[ 1.  2.  1.]
 [ 0.  2. -2.]
 [ 0.  4.  1.]]
[[ 1.  2.  1.]
 [ 0.  2. -2.]
 [ 0.  0.  5.]]


In [38]:
#Sneak peak at the next lesson:
print(E21)
#To get the inverse of E21, you would have to add 3 times instead of substract
Emin1 = I
Emin1[1,0] = 3
print(Emin1)
result_inverse = Emin1 @ E21
print(result_inverse)

[[ 1.  0.  0.]
 [-3.  1.  0.]
 [ 0.  0.  1.]]
[[1. 0. 0.]
 [3. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
#Rec
A2 = np.array([[1,-1,-1,1],[2,0,2,0],[0,-1,-2,0],[3,-3,-2,4]])
print(A2)
b2 = np.array([0,8,-8,7])
solve(A2,b2)

[[ 1 -1 -1  1]
 [ 2  0  2  0]
 [ 0 -1 -2  0]
 [ 3 -3 -2  4]]


array([1., 2., 3., 4.])

In [97]:
#Or applying it fully like on paper
I = np.identity(4)
print(I)
E21 = np.copy(I)
E21[1,0] = -2
E21[3,0] = -3
print(E21)
E32 = np.copy(I)
E32[2,1] = 1/2
print(E32)
Eswap = np.copy(I)
Eswap[[2,3]] = Eswap[[3, 2]]
print(Eswap)
Result = Eswap @ E32 @ E21 @ A2
print(Result)
Right_Hand = Eswap @ E32 @ E21 @ b2
print(Right_Hand)
solve(Result, Right_Hand)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-3.  0.  0.  1.]]
[[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.5 1.  0. ]
 [0.  0.  0.  1. ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
[[ 1. -1. -1.  1.]
 [ 0.  2.  4. -2.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0. -1.]]
[ 0.  8.  7. -4.]


array([1., 2., 3., 4.])

In [102]:
#And it would look like this permutated, this isn't per say useful but it shows you that the last added collumn remains unchanged in similar opperations
b_collumn = np.array([[0],[8],[-8],[7]])
A_p = np.hstack((A2, b_collumn))
print(A_p)
Permutated_Result = Eswap @ E32 @ E21 @ A_p
print(Permutated_Result)
#slicing a collumn
slice = Permutated_Result[:,4]
print(slice)
#removing a collumn
Sliced_Result = np.delete(Permutated_Result, 4, axis=1)
print(Sliced_Result)
solve(Sliced_Result, slice)

[[ 1 -1 -1  1  0]
 [ 2  0  2  0  8]
 [ 0 -1 -2  0 -8]
 [ 3 -3 -2  4  7]]
[[ 1. -1. -1.  1.  0.]
 [ 0.  2.  4. -2.  8.]
 [ 0.  0.  1.  1.  7.]
 [ 0.  0.  0. -1. -4.]]
[ 0.  8.  7. -4.]
[[ 1. -1. -1.  1.]
 [ 0.  2.  4. -2.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0. -1.]]


array([1., 2., 3., 4.])