In [19]:
import numpy as np
from numpy.linalg import solve

In [25]:
A1 = np.array([[1,1,2],[2,1,3],[3,1,4],[4,1,5]])
print(A1)
#Can only be solved for AX=b if b is within it's collumn space
b1 = np.array([1,2,3,4])
print(b1)
#I will have to come back to this lecture once I have increased knowledge of the operations that allow me to formulate collumn and row spaces

[[1 1 2]
 [2 1 3]
 [3 1 4]
 [4 1 5]]
[1 2 3 4]
