In [1]:
#Import statements
import numpy as np

In [11]:
#Numpy Array
x1 = np.array([1,2,3])
print(x1)

[1 2 3]


In [29]:
#Multiple Dimension array
x2 = np.array([[1,2,3,4],[0,8,0,9]])
print(x2)

[[1 2 3 4]
 [0 8 0 9]]


In [17]:
#Get dimmension
x1.ndim

1

In [18]:
#Get shape
x2.shape

(2, 4)

In [20]:
#Get data type
x1.dtype

dtype('int64')

In [21]:
#Get itemsize
x2.itemsize

8

In [25]:
#Set datatype
x3 = np.array([1,2,3], dtype='int32')
x3.dtype

dtype('int32')

In [26]:
#Get total bytes
x2.nbytes

64

In [31]:
#Get element
x2[1,1]

8

In [32]:
#Get row
x2[1, :]

array([0, 8, 0, 9])

In [33]:
#Get collumn
x2[:, 1]

array([2, 8])

In [48]:
#Get range of a row
x2[1, 1:3]

array([8, 0])

In [50]:
#Edit element
x2[1,1] = 17
print(x2)

[[ 1  2  3  4]
 [ 0 17  0  9]]


In [59]:
# Matrix of 0s
np.zeros(3)
np.zeros((3,3))
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [62]:
#Ones
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
#Full like array
np.full_like(x2, 3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [66]:
#Random matrix
np.random.rand(3,3)

array([[0.86531041, 0.21172395, 0.05709066],
       [0.60628829, 0.88486905, 0.80894706],
       [0.29715764, 0.34967818, 0.30652342]])

In [67]:
#Random int matrix
np.random.randint(10, size=(3,3))

array([[1, 9, 0],
       [8, 7, 6],
       [3, 4, 6]])

In [68]:
#Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
#Repeating arrays
x4 = np.array([[1,2,3]])
x5 = np.repeat(x4, 3)
print(x5)
x6 = np.repeat(x4, 3, axis=0)
print(x6)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [75]:
#When two variables point at the same thing VS a copy
original = np.array([1,2,3])
copy = original
copy[1] = 99
print(original)
original2 = np.array([1,2,3])
copy2 = np.copy(original2)
copy2[1] = 99
print(original2)

[ 1 99  3]
[1 2 3]


In [82]:
#Mathematical opperations
a = np.array([1,2,3])
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
b = np.array([4,5,6])
print(a + b)
print(a * b)

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[5 7 9]
[ 4 10 18]


In [88]:
#Multiplying for linear algebra
dim1 = np.ones((2,3))
dim2 = np.full((3,2),2)
np.matmul(dim1,dim2)

array([[6., 6.],
       [6., 6.]])

In [90]:
#Determinant
dim3 = np.identity(3)
np.linalg.det(dim3)

1.0

In [91]:
#Statistics
stat1 = np.array([[1,2,3],[4,5,6]])
np.min(stat1)

1

In [92]:
np.max(stat1)

6

In [93]:
np.max(stat1, axis=1)

array([3, 6])

In [94]:
np.sum(stat1)

21

In [98]:
#Reorganizing arrays
org1 = np.array([[1,2,3,4],[5,6,7,8]])
print(org1)
org2 = org1.reshape(8,1)
print(org2)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [100]:
#Vertical stacking
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack([v1,v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
#Horizontal stacking
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6])

In [102]:
#Import data
np.genfromtxt('gen.txt', delimiter = ',')

array([1., 2., 3., 4.])

In [105]:
#Always casts as float, can convert with astype
gen = np.genfromtxt('gen.txt', delimiter = ',').astype('int32')
print(gen)

[1 2 3 4]


In [106]:
# Boolean operations
gen>2

array([False, False,  True,  True])

In [107]:
# Index by boolean parameters
gen[gen>2]

array([3, 4], dtype=int32)

In [109]:
# You can also index with lists
gen[[0,1,3]]

array([1, 2, 4], dtype=int32)

In [ ]:
# That concludes the absolute basics of NumPy