In [1]:
import numpy as np

In [13]:
#Finding the inverse step by step
A1 = np.array([[1,3],[2,7]])
print(A1)
I = np.identity(2)
print(I)
A1_a_I = np.hstack((A1,I))
print(A1_a_I)
E21 = np.copy(I)
E21[1,0] = -2
print(E21)
result = E21 @ A1_a_I
print(result)
E12 = np.copy(I)
E12[0,1] = -3
result = E12 @ result
print(result)

[[1 3]
 [2 7]]
[[1. 0.]
 [0. 1.]]
[[1. 3. 1. 0.]
 [2. 7. 0. 1.]]
[[ 1.  0.]
 [-2.  1.]]
[[ 1.  3.  1.  0.]
 [ 0.  1. -2.  1.]]
[[ 1.  0.  7. -3.]
 [ 0.  1. -2.  1.]]
