In [2]:
import numpy as np

In [13]:
#Example 1:
# 2x-y = 0
# -x + 2y = 3
# A X = b
A1 = np.array([[2,-1],[-1,2]])
print(A1)
X1 = np.array([["x"],["y"]])
print(X1)
b1 = np.array([[0],[3]])
print(b1)
#In numpy these will be represented as follows:
A1 = np.array([[2,-1],[-1,2]])
print(A1)
b1 = np.array([0,3])
print(b1)
#And solved as follows:
print(np.linalg.solve(A1,b1))

[[ 2 -1]
 [-1  2]]
[['x']
 ['y']]
[[0]
 [3]]
[[ 2 -1]
 [-1  2]]
[0 3]
[1. 2.]


In [20]:
#For ease of use:
from numpy.linalg import solve
#Example 2:
A2 = np.array([[2,-1,0],[-1,2,-1],[0,-3,4]])
b2 = np.array([0,-1,4])
solve(A2,b2)

array([0., 0., 1.])