In [1]:
import numpy as np

In [13]:
#Solving AX=0
A1 = np.array([[1,2,2,2],[2,4,6,8],[3,6,8,10]])
print(A1)
#Elimination, skipping 0 as pivots
A1[1] -= 2 * A1[0]
A1[2] -= 3 * A1[0]
print(A1)
#And again but this time we shift the pivot because it cant be 0
A1[2] -= A1[1]
print(A1)
# [1,1] and [2,3] are our pivots here => rank = 2 and we will have 2 free rows, thus we have 2 special solutions
# We can choose arbitrary values for the free rows, these become our special solutions, example:
Special1 = np.array(['x1', 1, 'x3', 0])
Special2 = np.array(['x1', 0, 'x3', 1])
print(Special1)
print(Special2)


[[ 1  2  2  2]
 [ 2  4  6  8]
 [ 3  6  8 10]]
[[1 2 2 2]
 [0 0 2 4]
 [0 0 2 4]]
[[1 2 2 2]
 [0 0 2 4]
 [0 0 0 0]]
['x1' '1' 'x3' '0']
